development:
  adapter: postgresql
  encoding: unicode
  database: coin2usd
  pool: 12
  username: coin2usd
  password:
  host: localhost
  port: 5432

test: &test
  adapter: postgresql
  encoding: unicode
  database: coin2usd_test
  pool: 5
  username: coin2usd
  password:
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: coin2usd
  pool: 5
  username: coin2usd
  password:
